version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DBInmerso 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/mi_script.sql

  python_add:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres 