version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DBInmerso 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python_00:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres 
  
  #jupyter:
   # container_name: jupyter_notebookd
    #image: jupyter/base-notebook:latest
    #build: ./jupyter
    
   # depends_on:
    #  - postgres
    #volumes:
     #- ./scoring_jupyter.ipynb:/home/jovyan/work/datos/
    # - ./scoring_jupyter.ipynb:/home/jovyan/work/
   ##ports:
     # - "10000:8888"