version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DBInmerso 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python_a:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres 
  
  jupyter:
    image: jupyter/base-notebook:latest
    volumes:
      - ./scoring_jupyter.ipynb:/home/jovyan/work
    ports:
      - "8888:8888"