version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DBInmerso 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python_bbdd212r553:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres 
  
 