-- DROP TABLE IF EXISTS
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS HISTORIAL_USUARIOS;
DROP TABLE IF EXISTS RENTA;
DROP TABLE IF EXISTS RESOLUCION_SOLICITUDES;
DROP TABLE IF EXISTS SCORING;
DROP TABLE IF EXISTS TIPO_RESOLUCION;
DROP TABLE IF EXISTS DESTINOS;
DROP TABLE IF EXISTS DISCAPACIDAD;
DROP TABLE IF EXISTS FAMILIA_NUMEROSA;
DROP TABLE IF EXISTS PATRIMONIO;
DROP TABLE IF EXISTS USUARIOS;

-- CREATE TABLES
CREATE TABLE USUARIOS (
    DNI VARCHAR(10) PRIMARY KEY,
    Nombre VARCHAR(255),
    Apellido VARCHAR(255),
    Edad INT,
    Fecha_de_nacimiento DATE,
    ID_Solicitud INT,
    Usuario_solicitante VARCHAR(255)
);

CREATE TABLE HISTORIAL_USUARIOS (
    DNI VARCHAR(10) PRIMARY KEY,
    Cross_selling BOOLEAN,
    Resultado_solicitud_t_1 VARCHAR(255),
    Viajes_t_1 INT,
    Resultado_solicitud_t_2 VARCHAR(255),
    Viajes_t_2 INT,
    Suma_viajes_t_1_y_t_2 INT,
    Scoring_ind_participacion_previa INT
);

CREATE TABLE RENTA (
    DNI VARCHAR(10) PRIMARY KEY,
    Ingresos INT
);

CREATE TABLE RESOLUCION_SOLICITUDES (
    ID_Solicitud INT PRIMARY KEY,
    Anyo_solicitud INT,
    Usuarios_sol VARCHAR(255),
    Renta_sol INT,
    Primera_opcion VARCHAR(255),
    Segunda_opcion VARCHAR(255),
    Tercera_opcion VARCHAR(255)
);

CREATE TABLE TIPO_RESOLUCION (
    ID_Resolucion INT PRIMARY KEY,
    Tipo_resolucion VARCHAR(255)
);

CREATE TABLE DESTINOS (
    ID_Destinos INT PRIMARY KEY,
    Tipo_destino VARCHAR(255),
    Plazas_destino INT
);

CREATE TABLE DISCAPACIDAD (
    DNI VARCHAR(10) PRIMARY KEY,
    Grado_dis INT
);

CREATE TABLE FAMILIA_NUMEROSA (
    DNI VARCHAR(10) PRIMARY KEY,
    Tipo_fam_num VARCHAR(255)
);

CREATE TABLE PATRIMONIO (
    DNI VARCHAR(10) PRIMARY KEY,
    Valoracion_patrimonio INT
);
