-- Eliminar la tabla si ya existe y luego crearla
DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
    DNI VARCHAR(10) PRIMARY KEY,
    Nombre VARSCHAR(10),
    Apellido VARCHAR(10),
    edad INT
);

DROP TABLE IF EXISTS SOLICITUDES;
CREATE TABLE SOLICITUDES (
    DNI VARCHAR(10) PRIMARY KEY,
    Primera_opcion VARCHAR(10),
    Segundo_opcion VARCHAR(10),
    Tercera_opcion VARCHAR(10)
);

DROP TABLE IF EXISTS DISCAPACIDAD;
CREATE TABLE DISCAPACIDAD (
    DNI VARCHAR(10) PRIMARY KEY,
    Tipo VARCHAR(10)
);

DROP TABLE IF EXISTS TIPO_DISCAPACIDAD;
CREATE TABLE TIPO_DISCAPACIDAD (
    DNI VARCHAR(10),
    ID_Tipo VARCHAR(10),
    Grado INT
);

DROP TABLE IF EXISTS UNIDAD_FAMILIAR;
CREATE TABLE UNIDAD_FAMILIAR (
    DNI VARCHAR(10) PRIMARY KEY,
    Estado_civil VARCHAR(20)
);

DROP TABLE IF EXISTS PENSION;
CREATE TABLE PENSION (
    DNI VARCHAR(10) PRIMARY KEY,
    pension INT
);

DROP TABLE IF EXISTS PARTICIPACION;
CREATE TABLE PARTICIPACION (
    DNI VARCHAR(10) PRIMARY KEY,
    PARTICIPADO BOOLEAN,
    ULTIMA_FECHA DATE
);